name: ScenarioManager
author: Caleb Bassham
version: 1.0.0
main: me.calebbassham.scenariomanager.BukkitPlugin

depend:
  - PluginMessageFormat
  - SettingsManagerLib

commands:
  scenariomanager:
    aliases: [sm, scen]